@startuml
|End User|
start
:1. User initiates Permission Process;
|EDA/Permission Administrator|
|Eligible Party|
:2. Eligible Party receives data;
:3. Eligible Party creates Permission Request;
:4. Eligible Party validates Permission Request;
:5. Send Permission Request;
|EDA/Permission Administrator|
:6. Receive Permission Request;
if (EDA Validates Request?) then (yes)
else (no)
  :7. Send Rejected Message;
  |Eligible Party|
  :8. Receive Rejected Message;
  stop
endif
split
  |EDA/Permission Administrator|
  :9. Permission Request\nforwarded to End User;
  |End User|
  :10. End User responds\n(Accept, Reject, Ignore);
  if (Accepted?) then (yes)
    |EDA/Permission Administrator|
    :11. Send Accepted Message\nto Eligible Party;
    |Eligible Party|
    :12. Receive Accepted Message;
    stop
  else (no/ignored)
    |EDA/Permission Administrator|
    :13. Send Rejected Message to Eligible Party;
    |Eligible Party|
    :14. Receive Rejected Message;
    stop
  endif
split again
  |EDA/Permission Administrator|
  :15. Send Acknowledgment\nto Eligible Party;
  |Eligible Party|
  :16. Receive Acknowledgment;
  detach
end split
@enduml