@startuml
|End User|
start
:User initiates Permission Process;
|EDA/Permission Administrator|
|Eligible Party|
:Eligible Party receives data;
:Eligible Party creates Permission Request;
:Send Permission Request;
|EDA/Permission Administrator|
:Receive Permission Request;
if (EDA Validates Request?) then (yes)
else (no)
  :Send Rejected Message;
  |Eligible Party|
  :Receive Rejected Message;
  stop
endif
split
  |EDA/Permission Administrator|
  :Permission Request\nforwarded to End User;
  |End User|
  :End User responds\n(Accept, Reject, Ignore);
  if (Accepted?) then (yes)
    |EDA/Permission Administrator|
    :Send Accepted Message\nto Eligible Party;
    |Eligible Party|
    :Receive Accepted Message;
    stop
  else (no/ignored)
    |EDA/Permission Administrator|
    :Send Rejected Message to Eligible Party;
    |Eligible Party|
    :Receive Rejected Message;
    stop
  endif
split again
  |EDA/Permission Administrator|
  :Send Acknowledgment\nto Eligible Party;
  |Eligible Party|
  :Receive Acknowledgment;
  detach
end split
@enduml