@startuml
autonumber

actor user as "End User"
participant ep as "Eligible Party"
participant dso as "Datadis"

user -> ep++ : Initialize Process\nwith NIF, CUPS and Timeframe
ep -> ep : Create Permission Request
ep -> ep : Validate Permission Request
ep --> dso++ : Send Permission Request
ep --> user : Redirect to Datadis Portal
user -> dso : Get Permission Request
dso --> user-- : Return Permission Request

loop While Datadis API is not authorized
  ep -> dso: Request Data
  alt Is Authorized
    dso --> ep : Return Data
    ep -> ep : Permission Request Accepted
  else Is Not Authorized
    dso --> ep : Return not authorized
    alt Is Timeout reached
      ep -> ep : Permission Request Time Out
    end
  end
end

@enduml
